procnanny: testfork.c
	gcc -Wall -DMEMWATCH -DMW_STDIO -o procnanny testfork.c memwatch.c
clean:
	rm testfork *.o core
#testfork: testfork.c
#replace with gcc -o -Wall -g testfork testfork.c
#./testfork
