procnanny: testfork.c
	gcc -Wall -DMEMWATCH -DMW_STDIO -g -o procnanny testfork.c memwatch.c
clean:
	rm -f procnanny *.o core
#testfork: testfork.c
#replace with gcc -o -Wall -g testfork testfork.c
#./testfork
